name: .NET Core

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Caching
        id: mycache
        uses: actions/cache@v2
        with:
          path: ./Application/obj
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Install dependencies
        if: steps.mycache.outputs.cache-hit != 'true'
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore ./Application/Application.csproj
      - name: Publish
        run: dotnet publish -c Release
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: publish
          path: Application/bin/Release/netcoreapp3.1/publish
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Aws Deploy
        uses: cschleiden/webdeploy-action@v1
        with:
          webSiteName: 'http://ec2-3-129-92-50.us-east-2.compute.amazonaws.com/'
          package: ${{ format('{0}devops-dotnet/Application/bin/Release/netcoreapp3.1/publish', runner.workspace) }}
