name: .NET Core

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Caching
        id: mycache
        uses: actions/cache@v2
        with:
          path: ./Application/obj
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Install dependencies
        if: steps.mycache.outputs.cache-hit != 'true'
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore ./Application/Application.csproj
      - name: Publish
        run: dotnet publish -c Release
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: publish
          path: Application/bin/Release/netcoreapp3.1/publish
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Aws Deploy
        id: deploy
        uses: webfactory/create-aws-codedeploy-deployment@v0.2.2
      - uses: peter-evans/commit-comment@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            body: |
                @${{ github.actor }} this was deployed as [${{ steps.deploy.outputs.deploymentId }}](https://console.aws.amazon.com/codesuite/codedeploy/deployments/${{ steps.deploy.outputs.deploymentId }}?region=eu-central-1) to group `${{ steps.deploy.outputs.deploymentGroupName }}`.
