name: .NET Core

on:
  push:
    branches: [devlopment]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Caching
        id: mycache
        uses: actions/cache@v2
        with:
          path: ./Application/obj
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Install dependencies
        if: steps.mycache.outputs.cache-hit != 'true'
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore ./Application/Application.csproj
      - name: Publish
        run: dotnet publish
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: publish
          path: Application/bin/Debug/netcoreapp3.1/publish
