name: .NET Core

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Caching
        id: mycache
        uses: actions/cache@v2
        with:
          path: ./obj
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Install dependencies
        if: steps.mycache.outputs.cache-hit != 'true'
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore ./Application/Application.csproj
